# Custom Language File for Launcher Customizer

[ejs.app]
title = "YayoLauncher"

[ejs.landing]
mediaHomeURL = "https://yayokorea.net"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "https://github.com/yayokorea/YayoLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/yayokorea/YayoLauncher"
supportLink = "https://github.com/yayokorea/YayoLauncher/issues"

[ejs.welcome]
welcomeHeader = "YayoLauncher"
welcomeDescription = "야요의 마인크래프트 런쳐"
welcomeDescCTA = "야요의 마인크래프트 런쳐를 사용해보세요."
